
{{ config(materialized='table') }}

select  
"BASICPROC_STANDARD"    as BASICPROC_STANDARD
,"BASICSCAN_STANDARD" as BASICSCAN_STANDARD
,"BASICWRAP_STANDARD" as BASICWRAP_STANDARD
,"BASICPACK_STANDARD" as BASICPACK_STANDARD
,"BELT_STANDARD" as BELT_STANDARD
,"BLOUSE_STANDARD" as BLOUSE_STANDARD
,"COAT_STANDARD" as COAT_STANDARD
,"DRESS_STANDARD" as DRESS_STANDARD
,"FOOTWEAR_STANDARD" as FOOTWEAR_STANDARD
,"HEADWEAR_STANDARD" as HEADWEAR_STANDARD
,"HOSIERY_STANDARD" as HOSIERY_STANDARD
,"JACKET_STANDARD" as JACKET_STANDARD
,"NECKWEAR_STANDARD" as NECKWEAR_STANDARD
,"PANT_STANDARD" as PANT_STANDARD
,"SKIRT_STANDARD" as SKIRT_STANDARD
,"SWEATER_STANDARD" as SWEATER_STANDARD
,"TSHIRT_STANDARD" as TSHIRT_STANDARD
,"UNDERWEAR_STANDARD" as UNDERWEAR_STANDARD
,"BAG_STANDARD" as BAG_STANDARD
,"GIFTITEM_STANDARD" as GIFTITEM_STANDARD
,"HANDWEAR_STANDARD" as HANDWEAR_STANDARD
,"SMALLGOOD_STANDARD" as SMALLGOOD_STANDARD
,"JEWELRY_STANDARD" as JEWELRY_STANDARD
,"SWIMWEAR_STANDARD" as SWIMWEAR_STANDARD

from {{ ref('packing_time_standards') }}